### ISSUE TITLE
Setup CI & add tests

### ISSUE THREAD

**Issue by ayan-b** [yunhailuo/xena-GDC-ETL#11]
`Travis` can be used as a CI provider and `pytest` can be used to test.

**Comment by ayan-b** [comment]
I will add some preliminary tests and set up a CI.

**Comment by yunhailuo** [comment]
Installed travis but not codecov. I'd prefer to do this carefully and see how it goes with travis first. Let me know if you think codecov is a must.

**Comment by ayan-b** [comment]
@yunhailuo Although codecov is not must but as the codebase would get larger I think it is important to keep track of code coverage.
