### ISSUE TITLE
search() uses GET even if method is not GET

### ISSUE THREAD

**Issue by roshnet** [yunhailuo/xena-GDC-ETL#21]
In `gdc.py`, `search()` will perform a GET request even if the request method is other than GET. Or, it will perform a GET request even if (say) `method='PUT'` is passed as an argument.

Location of fix: Code where `search()` sends request to get a table of results, line 229 as of [now](https://github.com/yunhailuo/xena-GDC-ETL/tree/919c375a402b08e0ec9a22831820ad152d553a54).

## Expected Behaviour
It should send a GET request only when method is 'GET'.

As of now, only GET and POST are being used.
The current code will create problems, if in future a method other than GET or POST is used.

**Comment by ayan-b** [comment]
Shouldn't it throwing an error?
https://github.com/yunhailuo/xena-GDC-ETL/blob/919c375a402b08e0ec9a22831820ad152d553a54/xena_gdc_etl/gdc.py#L214

**Comment by ayan-b** [comment]
@roshnet close this issue?
CC: @yunhailuo

**Comment by yunhailuo** [comment]
Close for now. Feel free to re-open it if you have a second opinion.

**Comment by roshnet** [comment]
Ah, sorry. I have been busy on some academic assignments these days, couldn't stay active much.
Will shortly work on this issue.

**Comment by roshnet** [comment]
> 
> 
> Isn't it throwing an error?
> 
> [xena-GDC-ETL/xena_gdc_etl/gdc.py](https://github.com/yunhailuo/xena-GDC-ETL/blob/919c375a402b08e0ec9a22831820ad152d553a54/xena_gdc_etl/gdc.py#L214)
> 
> Line 214 in [919c375](/yunhailuo/xena-GDC-ETL/commit/919c375a402b08e0ec9a22831820ad152d553a54)
>  raise ValueError('Invalide method: {}\n method must be either "GET" '

@ayan-b No, I checked, this does not give an error.

**Comment by ayan-b** [comment]
@roshnet I am getting this:
![DeepinScreenshot_select-area_20190416170150](https://user-images.githubusercontent.com/29725587/56206189-65f68c80-6069-11e9-98fd-6de56861a3f7.png)

**Comment by yunhailuo** [comment]
Maybe you can help elaborate the expected behavior, @roshnet ? For `search()`, only GET and POST are allowed. This is specified by [GDC](https://docs.gdc.cancer.gov/API/Users_Guide/Search_and_Retrieval/#components-of-a-request).

Or what's you proposed changed?

**Comment by roshnet** [comment]
The code is perfect for now. But, the issue lays focus on the situation when methods other than GET or POST are used in (possible) future manipulations.

What @ayan-b did is great, but is only limited to the PUT request method.
It would be better if all other request methods are disallowed.

However, as @yunhailuo tells, since we are restricted to using POST and GET, let's assume there's no chance we use request methods other than GET or POST.

I shall soon highlight what I mean, in a PR.
@ayan-b thanks for working on the issue!

**Comment by yunhailuo** [comment]
Thanks for your interests. Sounds good. Feel free to highlight what you meant.

I'm going to close this issue for now. We can open a new one if GDC changes their mind in the future and/or if you have other ideas.
